### PR TITLE
Add save on unexpected terminal exit

### PR DESCRIPTION
**Pull request by milto-github**
Catches SIGHUP signal sent to children when the terminal closes. Will only save if modifications were made.

### CODE REVIEW

**Review by ksteinfeldt — COMMENTED** [review]
I suggest saving to a backup file if SIGHUP is caught as opposed to saving to the same file. 

Maybe a swap file?

**Comment by milto-github** [comment]
This will also require the option to load a file once kilo has started and let the user decide, or explicitly create the backups and let them start kilo off those

**Comment by matthewrsj** [comment]
I like the idea of a backup file, since I often make changes I don't end up saving. 

The option to load the file when kilo starts would be nice, but not necessary, and can be added later. For now, the user can just check for their backup file and `mv .<backup-file> <original-file>` if they want to restore their changes.

That being said, if you want to implement the option to load the file on kilo start, feel free.

**Comment by milto-github** [comment]
Ok, I'm thinking time-stamped filenames if that's the case.

**Pull request closed without merging**
